### ISSUE TITLE
No sound from Solfege (debian)

### ISSUE THREAD

**Issue by patarapolw** [nickavem/toolboxexamples#3]
I create a `debbox` and `sudo apt-get install solfege solfege-doc pulseaudio`, then run `solfege` to test sound.

There is only a single clicking sound, followed by silence.

In contrast, my [x11docker](https://github.com/mviereck/x11docker) trick works with sound.

```sh
git clone https://github.com/mviereck/x11docker.git
 ./x11docker/x11docker --backend=podman --nxagent --pulseaudio --home -- --tmpfs /dev/shm -- localhost/solfege solfege
```

[Dockerfile](https://github.com/patarapolw/x11docker-apps/blob/main/solfege/Dockerfile)

**Comment by nickavem** [comment]
Hm. I am unable to reproduce this issue. What OS version are you using on the host?

**Comment by patarapolw** [comment]
On Silverblue on QEMU/KVM, Arch Linux host; somehow, the sound can get out even without `pactl`.

I tested Feodra Silverblue on a real machine. Now, I can't get the sound out, no matter debbox method or x11docker method.

Can you get the sound out at all?

**Comment by nickavem** [comment]
Very strange. Sound is working perfectly for me. Silverblue 34, correct?

**Comment by patarapolw** [comment]
Somehow, on this new booting, I can get sound perfectly, but there is another issue related to LOCALE not set.

```
$ toolbox enter debbox
$ solfege

(solfege:7228): Gtk-WARNING **: 21:25:53.590: Locale not supported by C library.
	Using the fallback 'C' locale.

Failed to run locale.setlocale(locale.LC_ALL, '') Will continue
without translated messages. This is not a bug in GNU Solfege. See the
README file for more details.

Ignored the following error:
Traceback (most recent call last):
  File "/usr/share/solfege/solfege/i18n.py", line 74, in setup
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Gdk-Message: 21:25:53.797: Window 0x1622320 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 21:25:53.797: Window 0x1622320 is a temporary window without parent, application will not be able to position it on screen.
Translations are disabled because your locale settings are broken.
This is not a bug in GNU Solfege, so don't report it. The README file
distributed with the program has some more details.
0.8320567607879639
all files parsed: 1.2649381160736084
```

It's easy to fix, though.

```sh
export LC_ALL=C
```

**Comment by nickavem** [comment]
> Somehow, on this new booting, I can get sound perfectly, but there is another issue related to LOCALE not set.

https://wiki.debian.org/Locale

**Comment by patarapolw** [comment]
Thanks

```sh
$ sudo apt-get install locales
$ sudo dpkg-reconfigure locales
```

As few as this works, although a little more may be done - https://wiki.debian.org/Locale#Standard
